### PR TITLE
GH-967 Fix role extraction logic in JmesPathOidcRoleExtractor, throw exception when fails.

### LINKED ISSUE #967: [Feature] Fix role extraction logic in JmesPathOidcRoleExtractor, throw exception when fails.

### PR DESCRIPTION
**Pull request by NikitaKirilloff**
close #967 

## Summary by CodeRabbit

* **Bug Fixes**
  * OpenID Connect role extraction now fails explicitly when a role cannot be determined from the authentication provider instead of silently falling back to a default role, surfacing an error for unresolved role extraction.

* **Tests**
  * Updated tests to assert that role extraction reports failures when role information is missing or unavailable.

### CODE REVIEW

File: master/src/test/java/com/axelixlabs/axelix/master/service/auth/oauth/JmesPathOidcRoleExtractorTest.java [hunk 1]
```diff
@@ -119,11 +120,8 @@ void shouldReturnViewerWhenBothSourcesDoNotProvideRole() {
             """);
         JmesPathOidcRoleExtractor extractor = new JmesPathOidcRoleExtractor(oidcClient, "roles[0]");
 
-        // when.
-        Role role = extractor.extractRole(tokens);
-
-        // then.
-        assertThat(role).isEqualTo(DefaultRole.VIEWER);
+        // when & then.
+        assertThatThrownBy(() -> extractor.extractRole(tokens)).isInstanceOf(OidcTokenExchangeException.class);
```
[the remark this answers is not in the document]
Comment (NikitaKirilloff) [reply master/src/test/java/com/axelixlabs/axelix/master/service/auth/oauth/JmesPathOidcRoleExtractorTest.java:124]: I don't think it's necessary

File: master/src/test/java/com/axelixlabs/axelix/master/service/auth/oauth/JmesPathOidcRoleExtractorTest.java
Comment (mipo256) [inline master/src/test/java/com/axelixlabs/axelix/master/service/auth/oauth/JmesPathOidcRoleExtractorTest.java]: Test name is incorrect now

Comment (mipo256) [inline master/src/test/java/com/axelixlabs/axelix/master/service/auth/oauth/JmesPathOidcRoleExtractorTest.java]: test name

**Review by mipo256 — APPROVED** [review]
